### ISSUE TITLE
StepTracker issue

### ISSUE THREAD

**Issue by ethanjamesauto** [cmoretti/APCSA_2019_FRQs#1]
Instance variables are not set to zero in the constructor.

**Comment by cmoretti** [comment]
Instance variables have default values upon declaration. [(Reference)](https://docs.oracle.com/javase/tutorial/java/nutsandbolts/variablesummary.html "Oracle docs")

For `int`, this value is `0`, so if the logic of the program is such that the variable should start at 0 -- which in fact is the case here -- there is no need to explicitly initialize the instance variable in the constructor. 

At the Reading, the scoring notes explicitly permitted this structure.
